services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.6
    container_name: ticker-house-clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # native TCP interface
    environment:
      CLICKHOUSE_DB: ticker_house
      CLICKHOUSE_USER: ticker
      CLICKHOUSE_PASSWORD: ticker
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - ./.clickhouse/data:/var/lib/clickhouse
      - ./.clickhouse/logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 10
